Fix test failure on Python 3.8
As I mentioned in the previous commit, Python 3.8 prints the first line
of a multiline statement instead of the last line:

      TypeError: Invalid test_suite, None, in tests2
      > ...find.py(NNN)find_suites()
    - -> % (suite, module_name)
    + -> raise TypeError(
      (Pdb) c
      EndRun raised

We don't need to care about that if we convert this to a single-line
statement.