Fix tests on PyPy
PyPy got a real curses module since version 2.0, and it so happens that
it raises AttributeError: _SpoofOut instance has no attribute 'fileno'
when you call curses.setupterm() from a doctest.

You can see the error at
https://travis-ci.org/zopefoundation/zope.testrunner/jobs/17257482

and you can see how different Python versions produce different
exceptions in this situation at https://gist.github.com/mgedmin/8559853